#version: '3.8'
#
#services:
#  springboot-app:
#    container_name: springboot_app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - h2db
#    networks:
#      - app-network
#    volumes:
#      - ./target:/app/target
#
#  h2db:
#    container_name: h2db
#    image: oscarfonts/h2
#    ports:
#      - "9092:9092"
#      - "8082:8082"
#    environment:
#      H2_OPTIONS: "-ifNotExists"
#    networks:
#      - app-network
#    volumes:
#      - h2-data:/data/h2db
#
#networks:
#  app-network:
#    driver: bridge
#
#volumes:
#  h2-data:


version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jobapp
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app_network
    restart: unless-stopped

  pgadmin4:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
